### ISSUE TITLE
Great bot

### ISSUE THREAD

**Issue by kevindemara** [SergheiPogor/AMF#2]
Everything seems to be working quite well, but there are a few minor issues.
1) The checkboxes for networks don't save and default back to the same, regardless of user input:
![image](https://user-images.githubusercontent.com/7482816/169193227-512ebe31-84b2-4a14-813d-23b08cc29ab7.png)

2) Several networks don't work - I think this may need an increased delay or it may be an actual addmefast issue as doing the task manually often fails as well.

I'm wondering if you're still working on other networks as well. I know this seems to be a fork/clone from frxangelz's bot, but it'd be awesome if you were planning on expanding to include some additional networks as rotating just a few cause flags for captchas and increase detection.

Thanks again for your work!

**Comment by SergiuPogorDev** [comment]
1. Issue will be fixed in the next release(planning on 21-22 May). Also, additional networks will be added.
2. Not sure what you mean network is not working if the bot makes the necessary action successfully but AddMeFast doesn't count them, then is not an issue on the bot side. Personally, I've tested manually, and for some action even if were done successfully AddMeFast don't count them. Usually, in this case, I change my accounts, for example, I notice if YouTube Account have already too many subscribers this issue appears very often.

Regarding solving the captcha, this was not included in my TODO list because:
- its needed only on YouTube view
- for solving captcha you need a Paid Captcha Solver(DeathByCaptcha or any other) and of course, it's cheap but still not free, not sure if is effective to use it. Solving Captcha using AI like YOLO its assuming more time and effort and a powerful PC(not sure if all users will use it)

If you have any ideas on how to bepass captcha please advice...

**Comment by kevindemara** [comment]
Yes, you're right - it's not the bot's issue. AMF is buggy in terms of confirming all likes/follows etc. The only time it seems to work consistently is if I increase the delay by a few seconds before closing.

Captchas are a tough issue. There are several solvers which are pretty cheap, but I'm not sure how easily they can be integrated via API into a chrome plugin. I've used them successfully with discord bots, but that's about it. Also, TikTok also requests captchas (similar to CMC) with the puzzle slider. I think the key here is to create fresh accounts for the networks regularly or find aged accounts if captchas can't be solved.

I noticed after the latest update that the bot is no longer accurately switching networks. It's basically ignoring the user input of the boxes checked and switching to primarily YouTube. I'm running in on VMware, so maybe that's a factor, but it shouldn't be. I've tested lately with the following settings and it's just loading YouTube/Twitter repeatedly:
![image](https://user-images.githubusercontent.com/7482816/171352600-35e48e48-a654-48d9-a175-ada7ac459f39.png)
Any ideas?

**Comment by kevindemara** [comment]
Still active project or you no longer updating? I'm open to working with you if you're still planning on pursuing this project.

**Comment by SergiuPogorDev** [comment]
Yes, still active.
and yes, we accept any help and collaboration, just open a PR with your idea/fix/branch

This is a free project so, I work on it only when I'm free from my other projects. 
Thanks for understanding and support.

**Comment by kevindemara** [comment]
Sounds good, appreciate your work. Did you have a chance to check out my last post regarding the network not switching based on the selected checkboxes? I've tested on multiple machines with the same results. I've tried to look at the code to fix it but haven't had any luck.

**Comment by SergiuPogorDev** [comment]
sorry no... I'm on vacation till 04 July. I will fix the issue after I will come back to day 'n' night coding routine :)

**Comment by SergiuPogorDev** [comment]
**Checkout latest release v1.0.2 from July 05, 2022**

Please read the careful README file before updating/using the script
This issue will be closed, if you get any other new issues, try steps from README.
If still not helping, open a new issue on GitHub with details(including steps to recreate the issue)
